[package]
name = "client-3dsdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.7.1"
serde = { version = "1.0.164", features = ["derive"] }
serde-xml-rs = { version = "0.6.0", optional = true }

[features]
xml = ["serde-xml-rs"]